### ISSUE TITLE
Deployment Schedule/Plan

### ISSUE THREAD

**Issue by aremu-smog** [webboss/otherfaces.tech#19]
Hi @Joponpin2000 and @Demoivre02 ,

It's my thought that we should focus on getting all the current tasks we have right now into staging this week and deploy to production.

We can then begin to pick up new tasks from next week. This includes my task for migrating the codebase to typescript as well. What do you guys think? Does it make sense.

**Comment by Demoivre02** [comment]
Yes boss, totally agree

**Comment by aremu-smog** [comment]
Hi @Demoivre02 and @Joponpin2000 regarding this. 

Can we target to get everything we have in code review to staging say by Friday?

So we can battle deployment over the weekend and have new stuffs by next week.

I am open to pair program with anyone to quickly 'sort' out code reviews/comments or help in any way I can.
